# Generated by Django 2.2.8 on 2020-05-09 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
