# Generated by Django 2.2.8 on 2020-05-11 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_game_game_over'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='game_over',
            field=models.BooleanField(default=False),
        ),
    ]
